spring:
  datasource:
    jdbcUrl: jdbc:oracle:thin:@//localhost:1521/XE
    username: fred   #investigate why nnection is not ew
    password: flintstone
    driverClassName: oracle.jdbc.OracleDriver
    schema: FRED
    minimumIdle: 0
    minimumPoolSize: 10
    maxLifetime: 840000
    connectionTimeout: 30000
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    generate-ddl: true
    hibernate:
      generate_statistics: true
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false
        format_sql: true
        dialect: org.hibernate.dialect.Oracle12cDialect